
let x1 =Number(prompt("quelle est la distance x1 "));
let x2 =Number(prompt("quelle est la distance x2 "));
let y1 =Number(prompt("quelle est la distance y1 "));
let y2 =Number(prompt("quelle est la distance y2 "));
let z1 =Number(prompt("quelle est la distance z1 "));
let z2 =Number(prompt("quelle est la distance z2 "));
let distance =Math.sqrt(((x2-x1)**2) + ((y2-y1)**2) +((z2-z1)**2 ));
console.log("la distance est:" , distance );


